### ISSUE TITLE
Yarn PnP support

### ISSUE THREAD

**Issue by koshic** [iambumblehead/resolvewithplus#58]
As a developer I want to use Yarn PnP in my projects, but resolvewithplus doesn't support it at all. As a result, it's impossible to use latest esmock versions.

From the API perspective, it's easy to add PnP support https://yarnpkg.com/advanced/pnpapi (really dirty example):
```js
const resolvewith = (moduleId, parent, opts) => {
  const pnp = require('pnpapi');
  try {
    const resolved = pnp.resolveRequest(moduleId, parent);
    if (resolved !== null) {
      console.log('RESOLVED!', resolved)
      return cache[moduleId+parent] = resolved
    }
  } catch {
  }

  let resolvedpath = cache[moduleId+parent]
  if (resolvedpath) return resolvedpath
```

Sadly, it's hard for me to find exact point where I can switch resolution mode depends on PnP mode flag. May be it's better to use something like that:
```js
const resolvewithClassic = ...
const resolvewithPnP = ...
const resolvewith = isPnPEnabled ? resolvewithPnP : resolvewithClassic
```

Also, it looks like that we can't use options (isbrowser, priority) because package.json will be processed by Yarn loader.

@iambumblehead what do you think? I can provide test repo with Yarn PnP enabled, but it may be not so easy to setup unit tests pipeline.

**Comment by koshic** [comment]
Thx for quick answer!

Yeah, I agree with that approach - to pass custom resolver to esmock instead of changing resolvewithplus. In the future, resolvewithplus (or esmock, doesn't matter) can include different resolution modes if you decide that many users want it, right?

What about API changes - I think your second option is totally ok, simple wrapper for non-trivial setup is not a big deal.

Also, I propose to slightly refactor resolvewithplus usage, and switch from resolvewith.iscoremodule to https://nodejs.org/dist/latest-v20.x/docs/api/module.html#moduleisbuiltinmodulename (only one concern - old Node versions compatibility), to simplify resolver contract. 

What is our next steps? I can create custom resolver for PnP and test in various projects, but I don't know when I can have enough time to create PR to esmock repo with unit tests (

**Comment by iambumblehead** [comment]
Thanks for the message and agreement on all points. In the next days, I could add custom-resolver PR to esmock following this example,
```javascript
const modulePnP = await esmock('../src/modulePnP.js', {
  '../src/moduleIdChildPnP.js' : () => ['a', 'b']
}, null, {
  resolvers: [ pnpapi.resolveRequest ]
})
```
Then additional resolvers could be added any time. Sync and Async resolvers could be supported, but initial PR might by sync-only to start.

**Comment by iambumblehead** [comment]
resolved with this release https://github.com/iambumblehead/esmock/releases/tag/v2.5.3
